const themes = {
  regular: {
    itemBackground: '#ffffff',
    grayText: '#707070',
    textColor: '#000000',
    imgWrapper: '#ffffff',

    menuItemBorder: '#d8d8d8',
    
    primaryColor: '#d359a6',
    primaryText: '#000000',
    highlightText: '#d359a6',
    primaryBack: '#ffffff',
    secondaryBack: "#f7f7f7",
    buttonBack: '#d359a6',
    hamburger: '#000000',
    balancesBack: '#ffffff',
    overviewPriceBack: '#ffffff',
    overviewPriceBorder: '#d359a6',
    overviewPrimaryText: '#d359a6',
    overviewSecondaryText: '#000000',
    overviewTransactionArrow: '#d359a6',
    overviewTransactionTimestamp: '#d359a6',
    overviewTransactionId: '#a2a2a2',
    overviewTransactionEnvelope: '#868686',
    manageTokenHighlight: '#d359a6',
  },
  dark: {
    itemBackground: '#35364e',
    grayText: '#aa91d8',
    textColor: '#ffffff',
    imgWrapper: '#7a7298',

    menuItemBorder: '#151519',
    
    primaryColor: '#3b2042',
    primaryText: '#d6d0e0',
    highlightText: '#ffffff',
    primaryBack: '#383250',
    secondaryBack: "#554f6d",
    buttonBack: '#d359a6',
    hamburger: '#ffffff',
    balancesBack: '#1d1e27',
    overviewPriceBack: '#35364e',
    overviewPriceBorder: '#8a2e87',
    overviewPrimaryText: '#ffffff',
    overviewSecondaryText: '#ffffff',
    overviewTransactionArrow: '#d6d0e0',
    overviewTransactionTimestamp: '#8f7ab7',
    overviewTransactionId: '#8f7ab7',
    overviewTransactionEnvelope: '#d6d0e0',
    manageTokenHighlight: '#d6d0e0',
  },
  waves: {
    itemBackground: '#ffffff',
    grayText: '#707070',
    textColor: '#ffffff',
    imgWrapper: '#ffffff',
    
    menuItemBorder: '#d8d8d8',
    
    primaryColor: '#0055ff',
    primaryText: '#000000',
    highlightText: '#0055ff',
    primaryBack: '#ffffff',
    secondaryBack: "#f7f7f7",
    buttonBack: '#0055ff',
    hamburger: '#000000',
    balancesBack: '#ffffff',
    overviewPriceBack: '#0055ff',
    overviewPriceBorder: '#0055ff',
    overviewPrimaryText: '#ffffff',
    overviewSecondaryText: '#ffffff',
    overviewTransactionArrow: '#0055ff',
    overviewTransactionTimestamp: '#0055ff',
    overviewTransactionId: '#a2a2a2',
    overviewTransactionEnvelope: '#868686',
    manageTokenHighlight: '#0055ff',
  }
};

export default themes;